### PR TITLE
UI: Permissions: List, Add, Edit and Delete

### PR DESCRIPTION
**Pull request by dvaldivia**
Screen Shot 2020-02-05 at 11 27 52 AM
Screen Shot 2020-02-05 at 11 27 47 AM
Screen Shot 2020-02-05 at 11 27 37 AM

### CODE REVIEW

**Comment by cesnietor** [comment]
COLUMN ACTION Is showing strings different to the ones shown when creating a permission. 
E.g. `All Actions `== `readwrite`
Screen Shot 2020-02-05 at 2 51 21 PM

**Comment by cesnietor** [comment]
Delete permission showing bucket message 
Screen Shot 2020-02-05 at 2 51 45 PM

**Comment by cesnietor** [comment]
The permission duplicated is not fixed.
Here I'm trying to create a permission with Deny  and yet it is being rejected.
Screen Shot 2020-02-05 at 2 55 47 PM

**Comment by cesnietor** [comment]
IF description too long, table goes bananas.
Screen Shot 2020-02-05 at 2 57 03 PM

**Comment by cesnietor** [comment]
If name too long, table goes bananas
Screen Shot 2020-02-05 at 2 58 02 PM

**Comment by dvaldivia** [comment]
@cesnietor 
Screen Shot 2020-02-05 at 3 06 36 PM

**Comment by dvaldivia** [comment]
@cesnietor 🍌🍌🍌🍌🍌🍌🍌🍌

**Comment by dvaldivia** [comment]
Screen Shot 2020-02-05 at 3 12 17 PM

**Review by Alevsk — DISMISSED** [review]

**Review by cesnietor — DISMISSED** [review]
please fix duplicated issue

**Review by cesnietor — APPROVED** [review]
LGTM

**Pull request merged**
