### PR TITLE
UI: Add, Delete and Paginate Buckets

### PR DESCRIPTION
**Pull request by dvaldivia**
Screen Shot 2020-02-03 at 4 18 13 PM
Screen Shot 2020-02-03 at 4 13 55 PM
Screen Shot 2020-02-03 at 4 13 58 PM
Screen Shot 2020-02-03 at 4 14 03 PM

### CODE REVIEW

**Review by cesnietor — CHANGES_REQUESTED** [review]
While listing buckets on the UI  server dies:
```
2020/02/04 19:25:20 /m3.PublicAPI/ListBuckets - 4b0651de-0d5b-44d0-8eb7-f9f38a327a62
panic: runtime error: slice bounds out of range [:-1]

goroutine 235 [running]:
github.com/minio/m3/api.(*server).ListBuckets(0xc00032de60, 0x1c7b560, 0xc00036a360, 0xc0000cacd0, 0xc00032de60, 0x0, 0x40)
	/go/src/github.com/minio/m3/api/api-public-bucket-grpc.go:120 +0x513
github.com/minio/m3/api/stubs._PublicAPI_ListBuckets_Handler.func1(0x1c7b560, 0xc00036a360, 0x18a27c0, 0xc0000cacd0, 0x2, 0xc000443580, 0x1c7b560, 0xc00036a360)
	/go/src/github.com/minio/m3/api/stubs/public_api.pb.go:3540 +0x89
github.com/minio/m3/api/authentication.PublicAuthInterceptor(0x1c7b560, 0xc00036a180, 0x18a27c0, 0xc0000cacd0, 0xc0001bc2a0, 0xc0001bc2c0, 0xc0003f2a80, 0x5469e8, 0x18684c0, 0xc00036a180)
	/go/src/github.com/minio/m3/api/authentication/authentication.go:124 +0xb3a
github.com/minio/m3/api/stubs._PublicAPI_ListBuckets_Handler(0x1943640, 0xc00032de60, 0x1c7b560, 0xc00036a180, 0xc000287c20, 0x1a663d0, 0x1c7b560, 0xc00036a180, 0xc000041840, 0xb)
	/go/src/github.com/minio/m3/api/stubs/public_api.pb.go:3542 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00031c840, 0x1c98ae0, 0xc0004ab980, 0xc000188e00, 0xc000457260, 0x28c2e18, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00031c840, 0x1c98ae0, 0xc0004ab980, 0xc000188e00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00046d820, 0xc00031c840, 0x1c98ae0, 0xc0004ab980, 0xc000188e00)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
```

Screen Shot 2020-02-04 at 11 30 36 AM

**Comment by cesnietor** [comment]
If bucket failed on deletion, the same error is being dragged and not reset.
Screen Shot 2020-02-04 at 11 37 54 AM

Screen Shot 2020-02-04 at 11 38 04 AM

**Comment by cesnietor** [comment]
Size should display either the unit [Bytes] or convert to MB or TB etc.
Also size should be rendered as 0 if bucketSize is not being sent on the rest response. Else it is shown as `empty`
Screen Shot 2020-02-04 at 11 40 52 AM

**Comment by cesnietor** [comment]
When there are no buckets it just displays a text.
Screen Shot 2020-02-04 at 11 51 04 AM

**Review by Alevsk — DISMISSED** [review]

**Comment by kaankabalak** [comment]
There still seems to be some issues with the pagination as when I have 6 buckets and I set the rows per page to 5, I still see all 6 buckets as follows:

Screen Shot 2020-02-04 at 5 46 33 PM

**Comment by dvaldivia** [comment]
@kaankabalak how did you reached that state?

**Comment by cesnietor** [comment]
Tested, LGTM @kaankabalak  I tested it but it works for me, it might be that you don't have the backend that was also updated here.

**Review by cesnietor — APPROVED** [review]

**Comment by kaankabalak** [comment]
Ok sounds good to me @cesnietor, thank you for letting me know 👍

**Pull request merged**
