### PR TITLE
remove some unnecessary code copied from mc

### PR DESCRIPTION
**Pull request by aead**
This commit removes some unnecessary code and
tries to clean some parts up. However, there are
still more things to remove (e.g. `S3 client
factory - that's not Go at all.)

### CODE REVIEW

**Comment by dvaldivia** [comment]
yes, initially we pulled code from `mc` to be able to use `madmin`, I'm wondering if we should instead add the support for madmin on `minio-go` and use that instead?

**Comment by harshavardhana** [comment]
> yes, initially we pulled code from `mc` to be able to use `madmin`, I'm wondering if we should instead add the support for madmin on `minio-go` and use that instead?

madmin requires server side deps that's why its kept inside minio server @dvaldivia - once we stabilize the madmin we can move to minio-go or a separate go package with semantic versioning. Unfortunately, right now too many things are changing.

**Comment by aead** [comment]
@dvaldivia At the current state we don't need behave the same way as the minio server. As long as the general m3 sdk API's are well-defined we can change e.g. logging later on easily.

**Comment by dvaldivia** [comment]
@harshavardhana yeah, let's use madmin in the mean while
@aead sent you a PR with some changes to address the build error

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
