### PR TITLE
Validate tenant short_name

### LINKED ISSUE #32: Validate Tenant Short Name on creation
We need to make sure the tenants being created have a valid short name as that's used as identifier and subdomain.

Add this validation as a function so it can be re-used in many places.

A valid tenant short name must:
- [ ] Is globally unique
- [ ] min 2 characters
- [ ] max 64 characters
- [ ] is only lowecase, numbers and dashes `[a-z0-9-]{2,64}`
- [ ] Not a reserved word: m3, kube-system, default, kube-public, kube-node-lease

### PR DESCRIPTION
**Pull request by u5surf**
Fix #32 
I added new function to validate tenant `short_name` in `./cluster/tenants.go`

### CODE REVIEW

**Comment by harshavardhana** [comment]
Please add a proper PR title @u5surf and thanks for sending a PR

**Comment by dvaldivia** [comment]
Thanks for your PR @u5surf, the project is still in it's infancy and not ready for external contribution, none the less we can take this PR if you are ok with giving MinIO the copyright of this code just as stated on the  license at the top of the files. Let me know.

**Comment by dvaldivia** [comment]
hey, can you please type `yes` or `no` :P

**Comment by u5surf** [comment]
@dvaldivia 
Sorry for the late reply, I have no problem about the license, please go ahead

**Review by dvaldivia — APPROVED** [review]
Thanks a lot for your contribution @u5surf !!! 本当にありがとうございます！

**Pull request merged**
